### ISSUE TITLE
McBoaty v5 : When workflow started edited prompts revert to the llm prompts in the upscaler

### ISSUE THREAD

**Issue by stdmffn** [MaraScott/ComfyUI_MaraScott_Nodes#174] opened 2024-11-19 01:34 UTC
McBoaty v5
I am running this in debian.  The edited cache file is updating and the ui fields have the edited prompts until I queue up a new job.  Then the original prompts replace the edited prompts.  Looking at the logs, the edited prompts are not being sent to the refiner.   It appears to be using the original prompts and the original denoise.

**Comment by MaraScott** [comment] 2024-11-20 13:22
Hi,

When updating the prompt and denoise, it triggers an api request, can you check in your browser console if you have any issue related to api request ?
Could you share the wf you are using + the prompt and denoise (screenshot maybe) for each tile so I can reproduce ?

**Comment by stdmffn** [comment] 2024-11-20 14:10
[mcboatyv5.json](https://github.com/user-attachments/files/17831835/mcboatyv5.json)
Thanks for looking into this.
I am pretty sure the api is working because I triggered it manually using the browser and the edited cache file is updating.  So the edited cache files (if I edit the denoise) show the correct edits, but when I start the workflow, the original prompts come back.  When I look at the log, the original prompts are what seem to be passed and if I test by putting the denoise at 1 for a tile and/or adding a weird prompt, I do not get a different tile.

**Comment by MaraScott** [comment] 2024-11-22 08:58
where can I found `SwarmInputFloat` Node ?

**Comment by MaraScott** [comment] 2024-11-22 13:45
Hi,

here is the output I have from your workflow. 

<details>
<summary>1st launch</summary>
<code>
[MaraScott][Node 377] McBoaty (Refiner) is starting to do its magic
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 1/16
Requested to load AutoencoderKL
Loading 1 new model
loaded completely 0.0 319.11416244506836 True
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 2/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 3/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 4/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 5/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 6/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 7/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 8/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 9/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 10/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 11/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 12/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 13/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 14/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 15/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 16/16
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 1/16 : 0.3 / a stuffed animal holding a yellow frisbee on top of a green background
[MaraScott][Node 377 - Canny Upscaling] tile 1/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 1/16
[MaraScott][Node 377 - Refining Upscaling] tile 1/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
Requested to load ControlNet
Loading 1 new model
loaded completely 0.0 2386.120147705078 True
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.82it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 2/16 : 0.3 / a stuffed animal on top of a yellow background
[MaraScott][Node 377 - Canny Upscaling] tile 2/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 2/16
[MaraScott][Node 377 - Refining Upscaling] tile 2/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.34it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 3/16 : 0.3 / "a stuffed animal holding a yellow and blue frisbee"
[MaraScott][Node 377 - Canny Upscaling] tile 3/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 3/16
[MaraScott][Node 377 - Refining Upscaling] tile 3/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.32it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 4/16 : 0.3 / "a stuffed animal holding a yellow frosted umbrella on top of a green background"
[MaraScott][Node 377 - Canny Upscaling] tile 4/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 4/16
[MaraScott][Node 377 - Refining Upscaling] tile 4/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.33it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 5/16 : 0.3 / a stuffed animal on top of a green background
[MaraScott][Node 377 - Canny Upscaling] tile 5/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 5/16
[MaraScott][Node 377 - Refining Upscaling] tile 5/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.33it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 6/16 : 0.3 / a stuffed animal on top of a green background
[MaraScott][Node 377 - Canny Upscaling] tile 6/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 6/16
[MaraScott][Node 377 - Refining Upscaling] tile 6/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.31it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 7/16 : 0.3 / a stuffed animal sitting on top of a green background
[MaraScott][Node 377 - Canny Upscaling] tile 7/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 7/16
[MaraScott][Node 377 - Refining Upscaling] tile 7/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.05it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 8/16 : 0.3 / a stuffed animal on top of a green background
[MaraScott][Node 377 - Canny Upscaling] tile 8/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 8/16
[MaraScott][Node 377 - Refining Upscaling] tile 8/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.08it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 9/16 : 0.3 / Since the tile_prompt is describing something different from the full_image_prompt, I would correct the tile_prompt to match the full_image_prompt.

Here is the corrected tile_prompt:

"a stuffed animal"
[MaraScott][Node 377 - Canny Upscaling] tile 9/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 9/16
[MaraScott][Node 377 - Refining Upscaling] tile 9/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.15it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 10/16 : 0.3 / "a stuffed animal on top of a green background"
[MaraScott][Node 377 - Canny Upscaling] tile 10/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 10/16
[MaraScott][Node 377 - Refining Upscaling] tile 10/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.18it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 11/16 : 0.3 / "a stuffed animal"
[MaraScott][Node 377 - Canny Upscaling] tile 11/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 11/16
[MaraScott][Node 377 - Refining Upscaling] tile 11/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.18it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 12/16 : 0.3 / The tile_prompt "a blue and white photo of a blue and white object" is describing something different than the full_image_prompt "a stuffed animal on top of a green background".

Corrected tile_prompt: "a blue and white stuffed animal"
[MaraScott][Node 377 - Canny Upscaling] tile 12/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 12/16
[MaraScott][Node 377 - Refining Upscaling] tile 12/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.08it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 13/16 : 0.3 / The tile_prompt "a red and white photo of a green and white photo" is describing a photo within a photo, while the full_image_prompt "a stuffed animal on top of a green background" is describing a stuffed animal on a green background.

Corrected tile_prompt: "a stuffed animal on top of a green background"
[MaraScott][Node 377 - Canny Upscaling] tile 13/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 13/16
[MaraScott][Node 377 - Refining Upscaling] tile 13/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.19it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 14/16 : 0.3 / Since the tile_prompt is describing a part of the full_image_prompt, I won't change it. Here is the answer:

a pink doll with a pink ribbon on it's head
[MaraScott][Node 377 - Canny Upscaling] tile 14/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 14/16
[MaraScott][Node 377 - Refining Upscaling] tile 14/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.10it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 15/16 : 0.3 / The tile_prompt does not match the full_image_prompt, so it needs to be corrected. The corrected tile_prompt is:

"a stuffed animal on a green background"
[MaraScott][Node 377 - Canny Upscaling] tile 15/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 15/16
[MaraScott][Node 377 - Refining Upscaling] tile 15/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.02it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 16/16 : 0.3 / The tile_prompt "a red and white photo of a green and white photo" is describing a photo within a photo, while the full_image_prompt "a stuffed animal on top of a green background" is describing a stuffed animal on a green background.

Corrected tile_prompt: "a stuffed animal on top of a green background"
[MaraScott][Node 377 - Canny Upscaling] tile 16/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 16/16
[MaraScott][Node 377 - Refining Upscaling] tile 16/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.09it/s]
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 1/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 2/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 3/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 4/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 5/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 6/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 7/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 8/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 9/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 10/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 11/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 12/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 13/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 14/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 15/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 16/16
[MaraScott][Refining Upscaling] Rebuilding tile 1/16
[MaraScott][Refining Upscaling] Rebuilding tile 2/16
[MaraScott][Refining Upscaling] Rebuilding tile 3/16
[MaraScott][Refining Upscaling] Rebuilding tile 4/16
[MaraScott][Refining Upscaling] Rebuilding tile 5/16
[MaraScott][Refining Upscaling] Rebuilding tile 6/16
[MaraScott][Refining Upscaling] Rebuilding tile 7/16
[MaraScott][Refining Upscaling] Rebuilding tile 8/16
[MaraScott][Refining Upscaling] Rebuilding tile 9/16
[MaraScott][Refining Upscaling] Rebuilding tile 10/16
[MaraScott][Refining Upscaling] Rebuilding tile 11/16
[MaraScott][Refining Upscaling] Rebuilding tile 12/16
[MaraScott][Refining Upscaling] Rebuilding tile 13/16
[MaraScott][Refining Upscaling] Rebuilding tile 14/16
[MaraScott][Refining Upscaling] Rebuilding tile 15/16
[MaraScott][Refining Upscaling] Rebuilding tile 16/16
[MaraScott][Node 377] McBoaty (Refiner) is done with its magic
Prompt executed in 276.17 seconds
</code>
</details>

here the details of the wf I used for McBoaty

![image](https://github.com/user-attachments/assets/69816b53-7d83-4116-8614-a38383ef322c)

and the log for that modified version

<details>
<summary>2nd launch - modified prompt and denoise</summary>
<code>
[MaraScott][Node 432] McBoaty (PromptEditor) is starting to do its magic
[MaraScott][Node 432] McBoaty (PromptEditor) is done with its magic
[MaraScott][Node 377] McBoaty (Refiner) is starting to do its magic
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 1/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 2/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 3/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 4/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 5/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 6/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 7/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 8/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 9/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 10/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 11/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 12/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 13/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 14/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 15/16
[MaraScott][Node 377 - VAEEncodingTiled Upscaling] tile 16/16
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 1/16 : 0.76 / bird
[MaraScott][Node 377 - Canny Upscaling] tile 1/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 1/16
[MaraScott][Node 377 - Refining Upscaling] tile 1/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
Requested to load ControlNet
Loading 1 new model
loaded completely 0.0 2386.120147705078 True
loaded completely 11517.22873764038 4897.0483474731445 True
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.16it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 2/16 : 0.76 / bird
[MaraScott][Node 377 - Canny Upscaling] tile 2/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 2/16
[MaraScott][Node 377 - Refining Upscaling] tile 2/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.28it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 3/16 : 0.76 / bird
[MaraScott][Node 377 - Canny Upscaling] tile 3/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 3/16
[MaraScott][Node 377 - Refining Upscaling] tile 3/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.30it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 4/16 : 0.76 / bird
[MaraScott][Node 377 - Canny Upscaling] tile 4/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 4/16
[MaraScott][Node 377 - Refining Upscaling] tile 4/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.28it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 5/16 : 0.76 / bird
[MaraScott][Node 377 - Canny Upscaling] tile 5/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 5/16
[MaraScott][Node 377 - Refining Upscaling] tile 5/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.28it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 6/16 : 0.76 / bird
[MaraScott][Node 377 - Canny Upscaling] tile 6/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 6/16
[MaraScott][Node 377 - Refining Upscaling] tile 6/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.30it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 7/16 : 0.76 / bird
[MaraScott][Node 377 - Canny Upscaling] tile 7/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 7/16
[MaraScott][Node 377 - Refining Upscaling] tile 7/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.27it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 8/16 : 0.76 / bird
[MaraScott][Node 377 - Canny Upscaling] tile 8/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 8/16
[MaraScott][Node 377 - Refining Upscaling] tile 8/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.17it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 9/16 : 0.76 / bird
[MaraScott][Node 377 - Canny Upscaling] tile 9/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 9/16
[MaraScott][Node 377 - Refining Upscaling] tile 9/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.21it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 10/16 : 0.76 / bird
[MaraScott][Node 377 - Canny Upscaling] tile 10/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 10/16
[MaraScott][Node 377 - Refining Upscaling] tile 10/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.18it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 11/16 : 0.76 / bird
[MaraScott][Node 377 - Canny Upscaling] tile 11/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 11/16
[MaraScott][Node 377 - Refining Upscaling] tile 11/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.08it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 12/16 : 0.76 / bird
[MaraScott][Node 377 - Canny Upscaling] tile 12/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 12/16
[MaraScott][Node 377 - Refining Upscaling] tile 12/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.24it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 13/16 : 0.76 / bird
[MaraScott][Node 377 - Canny Upscaling] tile 13/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 13/16
[MaraScott][Node 377 - Refining Upscaling] tile 13/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.31it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 14/16 : 0.76 / bird
[MaraScott][Node 377 - Canny Upscaling] tile 14/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 14/16
[MaraScott][Node 377 - Refining Upscaling] tile 14/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.22it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 15/16 : 0.76 / bird
[MaraScott][Node 377 - Canny Upscaling] tile 15/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 15/16
[MaraScott][Node 377 - Refining Upscaling] tile 15/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.23it/s]
[MaraScott][Node 377 - Denoise/ClipTextEncoding Upscaling] tile 16/16 : 0.76 / bird
[MaraScott][Node 377 - Canny Upscaling] tile 16/16
[MaraScott][Node 377 - ControlNetApply Upscaling] tile 16/16
[MaraScott][Node 377 - Refining Upscaling] tile 16/16
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.29it/s]
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 1/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 2/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 3/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 4/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 5/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 6/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 7/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 8/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 9/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 10/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 11/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 12/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 13/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 14/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 15/16
[MaraScott][Node 377 - VAEDecodingTiled Upscaling] tile 16/16
[MaraScott][Refining Upscaling] Rebuilding tile 1/16
[MaraScott][Refining Upscaling] Rebuilding tile 2/16
[MaraScott][Refining Upscaling] Rebuilding tile 3/16
[MaraScott][Refining Upscaling] Rebuilding tile 4/16
[MaraScott][Refining Upscaling] Rebuilding tile 5/16
[MaraScott][Refining Upscaling] Rebuilding tile 6/16
[MaraScott][Refining Upscaling] Rebuilding tile 7/16
[MaraScott][Refining Upscaling] Rebuilding tile 8/16
[MaraScott][Refining Upscaling] Rebuilding tile 9/16
[MaraScott][Refining Upscaling] Rebuilding tile 10/16
[MaraScott][Refining Upscaling] Rebuilding tile 11/16
[MaraScott][Refining Upscaling] Rebuilding tile 12/16
[MaraScott][Refining Upscaling] Rebuilding tile 13/16
[MaraScott][Refining Upscaling] Rebuilding tile 14/16
[MaraScott][Refining Upscaling] Rebuilding tile 15/16
[MaraScott][Refining Upscaling] Rebuilding tile 16/16
[MaraScott][Node 377] McBoaty (Refiner) is done with its magic
</code>
</details>

2 things :

can you make sure to be up to date with all custom_nodes and ComfyUI and make sure this field is empty 

![image](https://github.com/user-attachments/assets/75069d4a-d55d-4d64-9a79-b0ff2f093930)

When I loaded the wf, this field had value `false` but it is suppose to be empty.

Not sure what happen there, I will check my own wf to be sure there is no issue there for some reason.

can you test again and let me know please ?

**Comment by MaraScott** [comment] 2024-12-19 15:41
This issue has been addressed in the McBoaty v6, the tilePrompt system is technically totally different, this issue won't be fixed in v5 though

![image](https://github.com/user-attachments/assets/ac59fbc4-ed79-4d0e-bba9-b024291c501a)

**Closed by MaraScott** 2024-12-19 15:41 UTC
Labels: documentation
