### ISSUE TITLE
cant install node..it keeps trying to log me into github

### ISSUE THREAD

**Issue by eranmahalu** [MaraScott/ComfyUI_MaraScott_Nodes#134] opened 2024-08-24 18:18 UTC
Hi,
When installing via comfyui manager, it doesnt work, nor does the try fix option...when i try via cmd it tells me to login to github, which doesnt help as well...any clues?

**Comment by MaraScott** [comment] 2024-08-24 22:05
Hmmm, that s weird.
First time I hear about such thing.
Can you try by uninstalling all other custom nodes aside of comfyui-manager and try install this one again and if it is still asking to connect to github I will need a Screencast of how it happen and a copy of your log please.

Have you try to download the zip from this repo and manually install it?

**Comment by eranmahalu** [comment] 2024-08-24 22:13
thanks for answering. I have a ton of custom nodes so I do not think this option is viable...but as for the other option - how do I manually install the zip file?

**Comment by MaraScott** [comment] 2024-08-24 22:20
You can move all your nodes, instead of deleting them, outside of the custom_nodes directory and it would do the same.
Otherwise, in github you have a code button on the top right, if you click on it you should see download zip.
Download it and unzip it in custom_nodes Dir, it should do the trick

**Comment by eranmahalu** [comment] 2024-08-24 22:21
no good...btw here is what I get
![Screenshot 2024-08-25 012015](https://github.com/user-attachments/assets/d6e8793f-f7ef-48b5-97b0-13bfb635d5cc)

**Comment by MaraScott** [comment] 2024-08-24 22:26
Do you have the log?
I need to be able to reproduce to fix it.

**Comment by eranmahalu** [comment] 2024-08-24 22:27
where do I pull it from?

**Comment by eranmahalu** [comment] 2024-08-24 22:29
[comfyui-logs-1724538495227.json](https://github.com/user-attachments/files/16738225/comfyui-logs-1724538495227.json)

**Comment by MaraScott** [comment] 2024-08-24 22:47
which tool are you using for that ?
I just tried on my computer and I don't face such thing
are you on local or elsewhere (lightning.ai etc...)

if I can t reproduce I can t help and right now I can't help much.

What I would do is to install a new version of comfyui and try to install this node alone, if you still have the issue I need to reproduce, if not the issue is elsewhere

**Comment by eranmahalu** [comment] 2024-08-25 05:54
I am using comfyui locally.

**Comment by eranmahalu** [comment] 2024-08-25 05:58
I think it has something to do with the version of comfy

**Comment by MaraScott** [comment] 2024-08-25 06:41
Okay, I'll close the issue then.
Feel free to comeback if you identify anything related the this node.

**Closed** 2024-08-25 06:41 UTC
